parent: "duvalhub/dummies-parent.yml"
app:
  version_control: maven
docker:
  registry: registry.swarmlocal4.duvalhub.com
  credentialId: DUVALHUB_PRIVATE_REGISTRY_CREDENTIALS
build:
  builder: maven
  builder_version: 3.9.12-eclipse-temurin-25-noble
  container: eclipse-temurin
  container_template: openjdk
  container_version: 25-jre-alpine
  destination: "target/*.jar"
deploy:
  database:
    enabled: true
  port: 8080
  platforms:
    base:
      baseDomainName: swarmlocal4.duvalhub.com
    dev:
      defaultHostname: true
    prod:
      host:
        url: swarmlocal4.duvalhub.com
